# Cloud Build configuration for automatic deployment
# This file is used by Cloud Build triggers to automatically deploy your application

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/kb-rag:$SHORT_SHA', '-f', 'Dockerfile.cloudrun', '.']
  
  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/kb-rag:$SHORT_SHA']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'kb-rag-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/kb-rag:$SHORT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--set-env-vars'
      - 'MONGODB_DB=rag_chatbot,KB_FOLDER=KB,TOKENIZERS_PARALLELISM=false'
      - '--update-secrets'
      - 'MONGODB_URI=mongodb-uri:latest,OPENAI_API_KEY=openai-api-key:latest'

substitutions:
  _REGION: us-central1

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/$PROJECT_ID/kb-rag:$SHORT_SHA'

